import type { Question } from "./types";

const q = (
  id: number, prompt: string, leftLabel: string, leftPrimary: Question["left"]["primary"], leftSecondary: Question["left"]["secondary"],
  rightLabel: string, rightPrimary: Question["right"]["primary"], rightSecondary: Question["right"]["secondary"],
): Question => ({
  id, prompt,
  left: { label: leftLabel, primary: leftPrimary, secondary: leftSecondary },
  right: { label: rightLabel, primary: rightPrimary, secondary: rightSecondary },
});

export const questions: Question[] = [
  q(1, "猫が膝の上で熟睡中。でもトイレが限界。", "ごめんね、と言ってどかす", "companionship", "affectionIntensity", "漏らす", "catPriority", "affectionIntensity"),
  q(2, "猫が布団のど真ん中で寝ている。", "ちょっとだけ詰めてもらう", "companionship", "freedomRespect", "空いている15cmで寝る", "catPriority", "touchDesire"),
  q(3, "猫が窓の外を真剣な顔で見ている。", "何を見てるのか、少し離れて観察する", "observation", "freedomRespect", "隣に座って同じ方向を見る", "companionship", "touchDesire"),
  q(4, "初対面の猫が3m先にいる。", "向こうが来るまで距離を詰めない", "freedomRespect", "observation", "しゃがんで交渉開始", "touchDesire", "affectionRange"),
  q(5, "旅先で、ひと目で「この子すごく好き」と思う猫に出会った。もう二度と会えないかもしれない。", "その場でたっぷり愛でて、思い出にする", "observation", "freedomRespect", "飼える可能性を考えはじめる", "affectionRange", "protectiveness"),
  q(6, "世界的に「最もかわいい猫」が決まったらしい。", "どんな猫なのか絶対見たい", "affectionRange", "observation", "うちの子がエントリーされていないので無効", "affectionIntensity", "companionship"),
  q(7, "「猫好きなんだね」と言われたら、感覚として近いのは？", "そう、猫ならだいたい好き", "affectionRange", "affectionIntensity", "猫好きというより、この子が好き", "affectionIntensity", "companionship"),
  q(8, "友達の猫の写真を見せてもらった。", "もっと写真を要求する", "observation", "affectionRange", "名前・年齢・性格まで聞く", "curiosity", "affectionRange"),
  q(9, "海外の知らない猫が、幸せそうに暮らしている動画が流れてきた。", "幸せそうでかわいい", "observation", "affectionRange", "安心する", "protectiveness", "affectionRange"),
  q(10, "道端の猫を見かけた。", "そっと見守って、そのまま通り過ぎる", "freedomRespect", "observation", "今日ちゃんと食べられているか気になる", "protectiveness", "affectionRange"),
  q(11, "猫の寝顔があまりにもかわいい。", "写真を撮って静かに眺める", "observation", "affectionIntensity", "宇宙に感謝する", "worship", "affectionIntensity"),
  q(12, "猫のお腹が目の前にある。", "見る。写真を撮る", "observation", "worship", "吸える条件が整っているなら吸う", "touchDesire", "affectionIntensity"),
  q(13, "猫から少し香ばしい匂いがする。", "いい匂いだなと思う", "worship", "affectionIntensity", "深く吸う", "touchDesire", "worship"),
  q(14, "猫のヒゲが床に落ちていた。", "見つけたことにちょっと喜ぶ", "observation", "affectionIntensity", "専用のヒゲ保管庫へ納める", "worship", "affectionIntensity"),
  q(15, "猫が謎の動きをしている。", "意味不明なまま眺めるのが楽しい", "observation", "worship", "なぜそうしたのか調べる", "curiosity", "companionship"),
  q(16, "猫の魅力をまだ知らない友達がいる。", "いつか猫の良さに気づく日を待つ", "freedomRespect", "affectionRange", "とりあえず私の猫フォルダを見せる", "evangelism", "affectionIntensity"),
  q(17, "猫の鳴き声が、いつもと少し違う気がする。", "しばらくそばで様子を見る", "observation", "freedomRespect", "何が違うのか原因を探りはじめる", "curiosity", "protectiveness"),
  q(18, "猫用品を選ぶとき。", "本人が気に入るかを最優先する", "freedomRespect", "companionship", "素材・安全性・レビュー・事故例まで調べる", "protectiveness", "curiosity"),
  q(19, "友達に「猫って何を考えてるか分からない」と言われた。", "そこも猫の魅力だと思う", "worship", "freedomRespect", "分かるようになるともっと面白いよ、と解説を始める", "evangelism", "curiosity"),
  q(20, "猫のために家の中を変えるなら。", "猫が好きな場所を選べるよう、人間の物を減らす", "freedomRespect", "catPriority", "危険箇所・温度・動線まで猫仕様にする", "protectiveness", "curiosity"),
  q(21, "出かける5分前に、猫が膝に乗ってきた。", "ごめんね、と言って予定どおり出かける", "companionship", "affectionIntensity", "この予定、本当に行く必要ある？と考えはじめる", "catPriority", "touchDesire"),
  q(22, "明日は朝6時起き。でも深夜1時、猫が猫じゃらしを持ってきた。", "明日遊ぶ約束をする", "companionship", "freedomRespect", "とことん付き合う", "catPriority", "affectionIntensity"),
  q(23, "猫に話しかけるとき、近いのは？", "「ご飯？」「眠い？」など、猫のことを話す", "protectiveness", "companionship", "今日あったことまで相談する", "companionship", "protectedFeeling"),
  q(24, "落ち込んでいると、猫が隣に来た。", "隣にいてくれるだけで元気が出る", "companionship", "affectionIntensity", "この子、私を心配して来てくれた", "protectedFeeling", "companionship"),
  q(25, "毎朝同じ時間に猫が起こしてくれる。", "ご飯の時間を覚えている", "curiosity", "companionship", "私の生活リズムまで管理してくれている", "protectedFeeling", "worship"),
  q(26, "お風呂に入ると、猫がドアの前で待っている。", "一緒にいたいのかなと思う", "companionship", "affectionIntensity", "私が溺れないか見張ってくれていると思う", "protectedFeeling", "worship"),
  q(27, "最高の猫動画を発見した。", "自分で何度も見る", "observation", "affectionIntensity", "だれかに共有する", "evangelism", "affectionRange"),
  q(28, "「猫ってそんなにかわいい？」と聞かれた。", "好みは人それぞれだと思う", "freedomRespect", "affectionRange", "座って。話はそこからです。", "evangelism", "worship"),
  q(29, "「猫って懐かないんでしょ？」と言われた。", "猫にもいろんな愛情表現があるよ、と伝える", "companionship", "freedomRespect", "とりあえず懐いている猫の証拠映像を見せる", "evangelism", "affectionRange"),
  q(30, "人類が猫に支配される未来が来た。", "人間と猫が対等に暮らす世界がいい", "companionship", "freedomRespect", "ようやく本来あるべき秩序になった", "worship", "catPriority"),
  q(31, "猫が何度も物を床に落としている。", "何で落とすのか観察する", "curiosity", "observation", "そこに物を置いた人間が悪いと思う", "worship", "catPriority"),
  q(32, "猫が作業を邪魔しに来た。", "「暇なの？」と遊びに誘う", "companionship", "touchDesire", "仕事を休めという猫からの啓示だと思う", "catPriority", "worship"),
  q(33, "目の前に100匹の猫がいる。", "一匹ずつ性格を観察したい", "curiosity", "observation", "全員今日から幸せにしたい", "protectiveness", "affectionRange"),
  q(34, "猫がいつものあなたの席で熟睡している。", "隣に自分の席を作る", "companionship", "touchDesire", "そこは今日から猫の席にする", "catPriority", "affectionIntensity"),
  q(35, "猫に手を舐められたら。", "毛づくろいしてもらう", "protectedFeeling", "touchDesire", "「どうしたの？」と聞く", "companionship", "curiosity"),
  q(36, "体調が悪くて寝ていると、猫がずっとそばにいる。", "今日は一緒にいたい日なんだと思う", "companionship", "affectionIntensity", "看病してくれていると思う", "protectedFeeling", "companionship"),
];
